# Generated by Django 5.0.9 on 2026-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('new_request', 'Yeni Sipariş'), ('cancelled', 'İptal'), ('payment', 'Ödeme'), ('driver_offline', 'Sürücü Çevrimdışı'), ('support', 'Şikayet / İstek'), ('general', 'Genel')], default='general', max_length=20),
        ),
    ]
