# Generated by Django 5.0.9 on 2026-08-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(choices=[('towing', 'Çekici'), ('roadside', 'Yol Yardım'), ('battery', 'Akü'), ('tire', 'Lastik'), ('fuel', 'Yakıt'), ('recovery', 'Kurtarma'), ('multi', 'Çoklu Araç Çekimi')], max_length=20, unique=True),
        ),
    ]
