# Generated by Django 5.0.9 on 2026-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.FloatField(default=0)),
                ('duration_minutes', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Talep Alındı'), ('searching', 'Operatör Aranıyor'), ('driver_found', 'Sürücü Bulundu'), ('en_route', 'Yolda'), ('arrived', 'Geldi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
