# Generated by Django 5.0.9 on 2026-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rating_comment',
            field=models.TextField(blank=True),
        ),
    ]
