# Generated by Django 5.0.9 on 2026-09-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_servicerequest_rating_servicerequest_rating_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('created', 'Talep Alındı'), ('searching', 'Operatör Aranıyor'), ('accepted', 'Teklif Kabul Edildi'), ('driver_found', 'Sürücü Bulundu'), ('en_route', 'Yolda'), ('arrived', 'Geldi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='created', max_length=20),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='requests.servicerequest')),
            ],
            options={
                'ordering': ('amount', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('request', 'driver'), name='unique_pending_offer_per_driver'),
        ),
    ]
