# Generated by Django 5.0.9 on 2026-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Nakit'), ('card', 'Kart')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
