# Generated by Django 5.0.9 on 2026-10-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0004_offer_and_accepted_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('complaint', 'Şikayet'), ('request', 'İstek'), ('suggestion', 'Öneri'), ('other', 'Diğer')], default='complaint', max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('mobile', 'Mobil Uygulama'), ('panel', 'Yönetici Paneli'), ('phone', 'Telefon'), ('other', 'Diğer')], default='mobile', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'İnceleniyor'), ('resolved', 'Çözüldü'), ('rejected', 'Reddedildi')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='requests.servicerequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_sup_status_52a4ed_idx'), models.Index(fields=['category', '-created_at'], name='support_sup_categor_09e769_idx')],
            },
        ),
    ]
